// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0-8leFlL8TonpKIw_eBIMM_XMXbhkVg',
    appId: '1:849952387694:web:fb3ad7d5cc92cede0a6c7f',
    messagingSenderId: '849952387694',
    projectId: 'resimblog',
    authDomain: 'resimblog.firebaseapp.com',
    storageBucket: 'resimblog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC5z4o6x9KRQFAas2lyVIFl_JtH92qYzc',
    appId: '1:849952387694:android:21a2350ad0e9a7b60a6c7f',
    messagingSenderId: '849952387694',
    projectId: 'resimblog',
    storageBucket: 'resimblog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt959PZwo9ZauEQ1N4xxq5oNoY3jYCQi0',
    appId: '1:849952387694:ios:6bce5258404968ac0a6c7f',
    messagingSenderId: '849952387694',
    projectId: 'resimblog',
    storageBucket: 'resimblog.appspot.com',
    iosBundleId: 'com.example.resimblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt959PZwo9ZauEQ1N4xxq5oNoY3jYCQi0',
    appId: '1:849952387694:ios:ccd3b0105e8464f30a6c7f',
    messagingSenderId: '849952387694',
    projectId: 'resimblog',
    storageBucket: 'resimblog.appspot.com',
    iosBundleId: 'com.example.resimblog.RunnerTests',
  );
}
